In [1]:
import sklearn
sklearn.__version__

'0.20.3'

In [8]:
from sklearn.cluster import KMeans
import numpy as np
X = np.array([[1, 2], [1, 4], [1, 0],
              [10, 2], [10, 4], [10, 0]])
kmeans = KMeans(n_clusters=2, random_state=0).fit(X)
print(kmeans.labels_)
r=kmeans.predict([[0, 0], [12, 3]])
print(r)
kmeans.cluster_centers_
#array([[10.,  2.],
  #     [ 1.,  2.]])

[1 1 1 0 0 0]
[1 0]


array([[10.,  2.],
       [ 1.,  2.]])